### ISSUE TITLE
Is `Assert.add` part of the public interface?

### ISSUE THREAD

**Issue by terinjokes** [bigpipe/assume#1]
I like what you've done so far with this project, and I've used it in a couple of my side projects so far. I'm interested in utilizing it in our main project, but we have custom assertions in our other library. Is `Assert.add` part of the public interface, or in another way, how are you thinking about a supporting custom assertions and/or plugins?

**Comment by 3rd-Eden** [comment]
@terinjokes Yes, the `assert.add` is part of the public API. It seems that I've forgotten to document it correctly. You can use this method to introduce new assertions in to the library. At this point I haven't came up with plugin structure yet. But at this point i'm just leaning towards a:

```js
var assume = require('assume');

assume.use(require('your-plugin'));
```

And `your-plugin` would be:

```js
module.exports = function (assume, helpers) {

});
```

Where `assume` is the reference to the `assume` instance and `helpers` is an object which exposes our internal helper like our object size calculation etc, array iterator, deep equal and more.

**Comment by terinjokes** [comment]
@3rd-Eden awesome. I was using for the very brief amount of time between when I started using these assertions and when you added `throws`.

I don't have any objection to the proposed plugin structure; it's seems to work elsewhere just fine.

**Comment by 3rd-Eden** [comment]
@terinjokes If you feel that certain assertions are missing in the library like `throws`, feel free to create an issue about that. I think it should be fairly complete right now.

Writing docs about the `add/use/alias` methods and i'll publish a `1.0` after it.

**Comment by terinjokes** [comment]
@3rd-Eden yes, I was going to send you a PR for it, but you had beat me to it. :+1:

That works for me, thanks for the quick responses!

**Comment by 3rd-Eden** [comment]
See new Plugin section in the documentation: https://github.com/bigpipe/assume#plugins
