### ISSUE TITLE
[feature request] assume(new Promise(...)).throws();

### ISSUE THREAD

**Issue by jonasfj** [bigpipe/assume#11]
It would be really neat if `assume(p).throws()` could assert that a promise is rejected/unfurfilled with an error.

Use case:

``` js
assume(asyncPromiseOperation(invalidInput)).throws();
```

It would also be cool, if `assume(f).throws()` would work with functions that returns promises.
Use case:

``` js
assume(async () => {
  while (true) {
    await asyncPromiseOperationThatSometimesFails(invalidInput);
  }
}).throws();
```

**Comment by jonasfj** [comment]
Maybe it needs another name but working with promises is going to be increasingly important in JS..
Maybe even a different design... I'm not sure what is best.. I just know that tests I currently write
I have too much try/catch in async functions to work around this...

(Async functions are just syntactic sugar for functions that returns promises)

**Comment by jcrugzz** [comment]
@jonasfj until we everyone is on `node@4.0.0` and later id say to implement this as a plugin for your use case. We provide an extensible API for this reason :).

**Comment by jhford** [comment]
looks like this was resolved... https://github.com/bigpipe/assume/#rejected-rejects-throwasync-throwsasync-failasync-failsasync

**Comment by 3rd-Eden** [comment]
That seems to be correct, if people disagree, feel free to create a new issue.
