### ISSUE TITLE
Dependencies gone: `is-node` and `prettify-error`

### ISSUE THREAD

**Issue by jonasfj** [bigpipe/assume#16]
Author unpublished his modules:
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.ylmv09gpm

Not exactly a nice thing to do... it also broke babel and a bunch of other modules.

The modules are probably published by someone else now.. But the old versions might not be there... So we probably have to upgrade the dependencies.

**Comment by 3rd-Eden** [comment]
Well, fuck.

**Comment by lpinca** [comment]
Module names have been promptly stolen ([prettify-error](https://www.npmjs.com/package/prettify-error), [is-node](https://www.npmjs.com/package/is-node)) making this even sadder.

**Comment by 3rd-Eden** [comment]
@lpinca Yep, I noticed the same thing. Which is horrible tbh. Now all they need to do is publish a package that does `rm -rf /` on install and the world is fucked.

**Comment by terinjokes** [comment]
@3rd-Eden this is why all the npm-compatible client alternatives don't run lifecycle scripts.

**Comment by lpinca** [comment]
I don't know if I should cry or laugh, seriously.

**Comment by 3rd-Eden** [comment]
Published 1.4.1 which no longer depends on azer's packages. But this still means that all previous versions are broken and dead. Yay..

**Comment by jonasfj** [comment]
Thanks for the fix... Now let's all just pretend this didn't happen :)

I guess using something like npm-lockdown is an option. But things like that is so painful...
