### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by ariutta** [bigpipe/assume#17]
```
npm install assume
```

yields this error:

> Error extracting /Users/XYZ/.npm/ansi-codes/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/XYZ/.npm/ansi-codes/0.0.0/package.tgz'

Installing directly from the repo works.

**Comment by 3rd-Eden** [comment]
The latest package is 1.4.1 - which also happens to be the last commit in our repository. So it makes absolutely no sense that master works while npm doesn't. You could try clearing your npm cache and see if that resolves the issue.

**Comment by ariutta** [comment]
The problem was in the [requests](https://github.com/unshiftio/requests/blob/master/package.json) library -- it depended on version 1.3.x.
