### ISSUE TITLE
increment `slice` when cloned?

### ISSUE THREAD

**Issue by terinjokes** [bigpipe/assume#3]
Working on my plugin, was wondering if it would make sense to increment the default value of `slice` to `this.test` when the assertion is cloned, as otherwise it makes the failure as with my plugin, rather than the entry point from the user.

**Comment by 3rd-Eden** [comment]
@terinjokes That is an excellent point. I'll see what I can do about this.

**Comment by 3rd-Eden** [comment]
So the commit above should add the desired functionality. Just got to write some tests for it, but you should be able to use it.

**Comment by terinjokes** [comment]
Nice! Thanks

**Comment by terinjokes** [comment]
@3rd-Eden should `eql` lose the "slice" argument, and `equals` implement the functionality with `this.clone`?

**Comment by 3rd-Eden** [comment]
@terinjokes Good point, we could just increment the internal `sliceStack` and lose the silly argument. I'll make the adjustments right away.
